services:
  postgres:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start --https-port=8443
    ports:
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: "false"

      KC_HTTPS_CERTIFICATE_FILE: /certs/llw.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /certs/llw.key

    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./llw.crt:/certs/llw.crt:ro
      - ./llw.key:/certs/llw.key:ro
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  keycloak_data: